name: Test
on: [push]
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run test
      - name: Upload coverage to Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          cd coverage
          SUMMARY_JSON=$(jq '{lines: .total.lines.pct, branches: .total.branches.pct}' coverage-summary.json)
          echo "$SUMMARY_JSON" > coverage-summary.json
          cat coverage-summary.json

          COVERAGE_JSON=$(cat coverage-summary.json | jq -c .)

          cat > payload.json << EOF
          {
            "files": {
              "coverage-summary.json": {
                "content": $COVERAGE_JSON
              }
            }
          }
          EOF
          
          curl -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            --data-binary @payload.json \
            https://api.github.com/gists/$GIST_ID
          
          rm payload.json
            